apiVersion: v1
kind: Service
metadata:
  name: myapp
#  annotations:
 #   service.beta.kubernetes.io/azure-load-balancer-internal: "true" Necesario si tienes un AKS configurado en una VNET (forma interna)
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
